_base_: configs/base.yaml
experiment_name: exp2_clip_ft_seed123
model:
  name: clip_finetune
  clip_model_name: ViT-B/16
loss:
  name: cross_entropy
train:
  per_gpu_batch: 128
  lr: 0.00002
  weight_decay: 0.0005
  epochs: 5
  patience: 3
  seed: 123
