_base_: configs/base.yaml
experiment_name: exp3_rawcls_normprompt_fullffpp_ema_s2048
model:
  name: clip_prompt
  clip_model_name: ViT-B/16
  classifier_normalize_features: false
loss:
  name: cross_entropy_plus_prompt
  beta: 0.1
  alpha: 0.3
  tau: 0.07
train:
  per_gpu_batch: 128
  lr: 0.00001
  weight_decay: 0.0005
  epochs: 15
  patience: 5
  warmup_epochs: 1
  ema_decay: 0.999
  seed: 2048
dataset:
  train_videos_per_method: 586
