_base_: configs/base.yaml
experiment_name: exp3_ema_lr75e6_w2
model:
  name: clip_prompt
  clip_model_name: ViT-B/16
loss:
  name: cross_entropy_plus_prompt
  beta: 0.1
  alpha: 0.3
  tau: 0.07
train:
  per_gpu_batch: 128
  lr: 0.0000075
  weight_decay: 0.0005
  epochs: 15
  patience: 5
  warmup_epochs: 2
  ema_decay: 0.999
  seed: 42
